// <auto-generated />
using System;
using BibliothequeVieuxMontreal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliothequeVieuxMontreal.Migrations
{
    [DbContext(typeof(biblioContext))]
    [Migration("20240509092843_bib")]
    partial class bib
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BibliothequeVieuxMontreal.Models.Livre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<string>("Cetegorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Livre", (string)null);
                });

            modelBuilder.Entity("BibliothequeVieuxMontreal.Models.Membre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Membre", (string)null);
                });

            modelBuilder.Entity("BibliothequeVieuxMontreal.Models.Pret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<int>("IdLivre")
                        .HasColumnType("int")
                        .HasColumnName("Id_livre");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int")
                        .HasColumnName("Id_membre");

                    b.HasKey("Id");

                    b.HasIndex("IdLivre");

                    b.HasIndex("IdMembre");

                    b.ToTable("Pret", (string)null);
                });

            modelBuilder.Entity("BibliothequeVieuxMontreal.Models.Retard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DatePret")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int>("IdLivre")
                        .HasColumnType("int")
                        .HasColumnName("Id_livre");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int")
                        .HasColumnName("Id_membre");

                    b.Property<int>("Nbjour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Retard", (string)null);
                });

            modelBuilder.Entity("BibliothequeVieuxMontreal.Models.Pret", b =>
                {
                    b.HasOne("BibliothequeVieuxMontreal.Models.Livre", "IdLivreNavigation")
                        .WithMany("Prets")
                        .HasForeignKey("IdLivre")
                        .IsRequired()
                        .HasConstraintName("FK__Pret__Id_livre__5FB337D6");

                    b.HasOne("BibliothequeVieuxMontreal.Models.Membre", "IdMembreNavigation")
                        .WithMany("Prets")
                        .HasForeignKey("IdMembre")
                        .IsRequired()
                        .HasConstraintName("FK__Pret__Id_membre__60A75C0F");

                    b.Navigation("IdLivreNavigation");

                    b.Navigation("IdMembreNavigation");
                });

            modelBuilder.Entity("BibliothequeVieuxMontreal.Models.Livre", b =>
                {
                    b.Navigation("Prets");
                });

            modelBuilder.Entity("BibliothequeVieuxMontreal.Models.Membre", b =>
                {
                    b.Navigation("Prets");
                });
#pragma warning restore 612, 618
        }
    }
}
